from __future__ import annotations

from typing import Any

from sketch2rhino import __version__

PRODUCT_NAME = "RU-LineArt"
SERVICE_NAME = "RU-LineArt API"
PROVIDER_NAME = "BEhop"
AUTHOR_NAME = "BEhop Design AI Lab"
BRAND_URL = "https://behop.cn"
LOG_PREFIX = "[BEhop AI]"


def brand_signature() -> dict[str, str]:
    return {
        "service": SERVICE_NAME,
        "provider": PROVIDER_NAME,
        "author": AUTHOR_NAME,
        "url": BRAND_URL,
    }


def generator_label() -> str:
    return f"{PRODUCT_NAME} {__version__}"


def generated_by_text() -> str:
    return f"Generated by {PROVIDER_NAME} AI Tool"


def build_tool_manifest(
    endpoint: str = "http://127.0.0.1:8000",
    *,
    openapi_path: str = "/openapi.json",
    convert_path: str = "/convert",
    health_path: str = "/health",
) -> dict[str, Any]:
    base = endpoint.rstrip("/")
    openapi = f"{base}{openapi_path}" if base else openapi_path
    convert = f"{base}{convert_path}" if base else convert_path
    health = f"{base}{health_path}" if base else health_path

    return {
        "name": PRODUCT_NAME,
        "service": SERVICE_NAME,
        "provider": PROVIDER_NAME,
        "author": AUTHOR_NAME,
        "url": BRAND_URL,
        "version": __version__,
        "endpoint": base,
        "openapi": openapi,
        "health": health,
        "tools": [
            {
                "name": "convert",
                "method": "POST",
                "path": convert_path,
                "description": "Convert sketch image to Rhino 3dm file",
                "url": convert,
            }
        ],
    }
